# Site settings
title: Jamie Gorson
email: jamie@gorsonfamily.com
description: My Portfolio
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jamiegorson.com" # the base hostname & protocol for your site
github_username:  jamiesarahg

# Build settings
markdown: kramdown
permalink: /:title.html
